export const GET_TODOS = 'GET_TODOS';
export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_ERROR = 'GET_TODOS_ERROR';

export const GET_TODO_BY_ID = 'GET_TODO_BY_ID';
export const GET_TODO_BY_ID_REQUEST = 'GET_TODO_BY_ID_REQUEST';
export const GET_TODO_BY_ID_SUCCESS = 'GET_TODO_BY_ID_SUCCESS';
export const GET_TODO_BY_ID_ERROR = 'GET_TODO_BY_ID_ERROR';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_ERROR = 'UPDATE_TODO_ERROR';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';

export const RESET_TODO_ERROR = 'RESET_TODO_ERROR';